import { requireAuth, logout } from "@/lib/auth";
import { getActivePlan, listPlans } from "@/lib/plans";
import { createAutoGeneratedPlan, createPlanFromTemplate } from "./plan-actions";

export const dynamic = "force-dynamic";

function formatDate(d: Date) {
  return d.toLocaleDateString(undefined, {
    month: "short",
    day: "numeric",
  });
}

export default async function DashboardPage() {
  const user = await requireAuth();
  const [activePlan, plans] = await Promise.all([
    getActivePlan(user.id),
    listPlans(user.id),
  ]);

  const today = new Date();

  const todaySession = activePlan?.sessions.find((s) => {
    const d = new Date(s.date);
    return (
      d.getFullYear() === today.getFullYear() &&
      d.getMonth() === today.getMonth() &&
      d.getDate() === today.getDate()
    );
  });

  return (
    <div className="space-y-6">
      <header className="flex flex-col gap-3 border-b border-slate-800 pb-4 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <p className="text-xs font-medium uppercase tracking-wide text-emerald-300">
            Dashboard
          </p>
          <h1 className="text-2xl font-semibold tracking-tight text-slate-50">
            Hey {user.name || user.email}, let&apos;s keep it simple.
          </h1>
          <p className="mt-1 text-sm text-slate-400">
            Follow a gentle beginner plan, one small step at a time.
          </p>
        </div>
        <form
          action={async () => {
            "use server";
            await logout();
          }}
        >
          <button
            type="submit"
            className="inline-flex items-center justify-center rounded-md border border-slate-700 px-3 py-1.5 text-xs font-medium text-slate-200 transition hover:border-slate-500 hover:bg-slate-900"
          >
            Log out
          </button>
        </form>
      </header>

      <section className="grid gap-4 md:grid-cols-3">
        <div className="space-y-2 rounded-xl border border-emerald-500/30 bg-slate-950/80 p-4 shadow-sm shadow-emerald-500/20">
          <p className="text-xs font-medium uppercase tracking-wide text-emerald-200">
            Today
          </p>
          {activePlan && todaySession ? (
            <>
              <p className="text-sm font-semibold text-slate-50">
                {todaySession.title}
              </p>
              <p className="text-xs text-slate-300">
                {todaySession.focus}
              </p>
              <p className="text-xs text-emerald-300">
                ~{todaySession.durationMinutes ?? 20} min · {activePlan.environment === "HOME" ? "At home" : "At the gym"}
              </p>
            </>
          ) : activePlan ? (
            <>
              <p className="text-sm font-semibold text-slate-50">
                Rest or light walk
              </p>
              <p className="text-xs text-slate-300">
                No scheduled session for today. A 5–10 minute walk still counts.
              </p>
            </>
          ) : (
            <>
              <p className="text-sm font-semibold text-slate-50">
                No plan yet
              </p>
              <p className="text-xs text-slate-300">
                Create a simple beginner plan below. It only takes a few
                seconds.
              </p>
            </>
          )}
        </div>
        <div className="space-y-2 rounded-xl border border-slate-800 bg-slate-950/80 p-4">
          <p className="text-xs font-medium uppercase tracking-wide text-slate-300">
            Habits
          </p>
          <p className="text-sm font-semibold text-slate-50">Coming soon</p>
          <p className="text-xs text-slate-400">
            You&apos;ll be able to tick off tiny daily habits like
            "+1 glass of water" or "5-minute stretch".
          </p>
        </div>
        <div className="space-y-2 rounded-xl border border-slate-800 bg-slate-950/80 p-4">
          <p className="text-xs font-medium uppercase tracking-wide text-slate-300">
            Weight & body
          </p>
          <p className="text-sm font-semibold text-slate-50">Coming soon</p>
          <p className="text-xs text-slate-400">
            You&apos;ll be able to log your weight and measurements here. No
            calorie counting, just simple progress.
          </p>
        </div>
      </section>

      <section className="grid gap-4 lg:grid-cols-[3fr,2fr]">
        <div className="space-y-4 rounded-xl border border-slate-800 bg-slate-950/80 p-4">
          <p className="text-xs font-semibold uppercase tracking-wide text-slate-300">
            Beginner workout planning
          </p>
          {activePlan ? (
            <div className="space-y-2 text-sm text-slate-200">
              <p className="font-semibold">Current plan</p>
              <p className="text-xs text-slate-300">
                {activePlan.name} · {activePlan.daysPerWeek} days/week · Starts {formatDate(new Date(activePlan.startDate))}
              </p>
              {activePlan.endDate && (
                <p className="text-xs text-slate-500">
                  Runs until {formatDate(new Date(activePlan.endDate))}
                </p>
              )}
            </div>
          ) : (
            <p className="text-sm text-slate-300">
              Choose a simple starter plan or answer 2 quick questions to
              auto-generate one.
            </p>
          )}

          <div className="grid gap-3 md:grid-cols-2">
            <form
              action={createPlanFromTemplate}
              className="flex flex-col gap-2 rounded-lg border border-slate-800 bg-slate-950/80 p-3 text-xs"
            >
              <p className="font-semibold text-slate-100">Pick a starter plan</p>
              <p className="text-slate-400">
                Choose between a no-equipment home plan or a simple gym plan.
              </p>
              <div className="space-y-1">
                <label className="flex items-center gap-2 text-slate-200">
                  <input
                    type="radio"
                    name="environment"
                    value="HOME"
                    defaultChecked
                    className="h-3 w-3 accent-emerald-500"
                  />
                  <span className="text-xs">Home – no equipment</span>
                </label>
                <label className="flex items-center gap-2 text-slate-200">
                  <input
                    type="radio"
                    name="environment"
                    value="GYM"
                    className="h-3 w-3 accent-emerald-500"
                  />
                  <span className="text-xs">Gym – machines first</span>
                </label>
              </div>
              <button
                type="submit"
                className="mt-1 inline-flex items-center justify-center rounded-md bg-brand-500 px-3 py-1.5 text-xs font-semibold text-slate-900 shadow-sm transition hover:bg-brand-600"
              >
                Create starter plan
              </button>
            </form>

            <form
              action={createAutoGeneratedPlan}
              className="flex flex-col gap-2 rounded-lg border border-slate-800 bg-slate-950/80 p-3 text-xs"
            >
              <p className="font-semibold text-slate-100">Auto-generate plan</p>
              <p className="text-slate-400">
                Answer two quick questions. We&apos;ll keep it very beginner
                friendly.
              </p>
              <div className="space-y-1">
                <p className="text-[11px] font-medium uppercase tracking-wide text-slate-400">
                  Where will you mostly work out?
                </p>
                <div className="flex flex-wrap gap-2">
                  <label className="flex items-center gap-1 rounded-full border border-slate-700 px-2 py-1 text-[11px]">
                    <input
                      type="radio"
                      name="environment"
                      value="HOME"
                      defaultChecked
                      className="h-3 w-3 accent-emerald-500"
                    />
                    Home
                  </label>
                  <label className="flex items-center gap-1 rounded-full border border-slate-700 px-2 py-1 text-[11px]">
                    <input
                      type="radio"
                      name="environment"
                      value="GYM"
                      className="h-3 w-3 accent-emerald-500"
                    />
                    Gym
                  </label>
                </div>
              </div>
              <div className="space-y-1">
                <label
                  htmlFor="daysPerWeek"
                  className="text-[11px] font-medium uppercase tracking-wide text-slate-400"
                >
                  How many days per week can you realistically move?
                </label>
                <select
                  id="daysPerWeek"
                  name="daysPerWeek"
                  className="w-full rounded-md border border-slate-800 bg-slate-900 px-2 py-1.5 text-xs text-slate-50 focus:border-emerald-500 focus:outline-none focus:ring-1 focus:ring-emerald-500/40"
                  defaultValue="3"
                >
                  <option value="2">2 days</option>
                  <option value="3">3 days</option>
                  <option value="4">4 days</option>
                </select>
              </div>
              <button
                type="submit"
                className="mt-1 inline-flex items-center justify-center rounded-md bg-slate-100 px-3 py-1.5 text-xs font-semibold text-slate-900 shadow-sm transition hover:bg-slate-200"
              >
                Generate gentle plan
              </button>
            </form>
          </div>
        </div>

        <div className="space-y-3 rounded-xl border border-slate-800 bg-slate-950/80 p-4">
          <p className="text-xs font-semibold uppercase tracking-wide text-slate-300">
            Your schedule
          </p>
          {activePlan ? (
            <ul className="max-h-72 space-y-1 overflow-auto pr-1 text-xs">
              {activePlan.sessions.slice(0, 21).map((session) => {
                const d = new Date(session.date);
                const isToday =
                  d.getFullYear() === today.getFullYear() &&
                  d.getMonth() === today.getMonth() &&
                  d.getDate() === today.getDate();

                return (
                  <li
                    key={session.id}
                    className={`flex items-center justify-between gap-2 rounded-md border px-2 py-1.5 ${
                      isToday
                        ? "border-emerald-500/60 bg-emerald-500/10"
                        : "border-slate-800 bg-slate-900/60"
                    }`}
                  >
                    <div>
                      <p className="text-[11px] font-medium text-slate-100">
                        {formatDate(d)} · Week {session.weekIndex + 1}
                      </p>
                      <p className="text-[11px] text-slate-300">
                        {session.title}
                      </p>
                    </div>
                    <a
                      href={`/dashboard/sessions/${session.id}`}
                      className="whitespace-nowrap rounded-full border border-emerald-500/70 bg-emerald-500/10 px-2 py-0.5 text-[10px] font-medium text-emerald-200 hover:bg-emerald-500/20"
                    >
                      Open
                    </a>
                    <p className="text-[10px] text-slate-400">
                      ~{session.durationMinutes ?? 20} min
                    </p>
                  </li>
                );
              })}
            </ul>
          ) : (
            <p className="text-xs text-slate-400">
              Once you create a plan, you&apos;ll see the next few weeks of gentle
              sessions here.
            </p>
          )}
        </div>
      </section>

      <section className="rounded-xl border border-slate-800 bg-slate-950/80 p-4">
        <p className="text-xs font-semibold uppercase tracking-wide text-slate-300">
          Phase 2: Beginner workout planning
        </p>
        <p className="mt-1 text-sm text-slate-300">
          You can now create simple beginner workout plans and see your
          upcoming schedule. Later phases will turn each session into a guided
          home workout with timers, plus habits and weight tracking.
        </p>
      </section>
    </div>
  );
}
