"use server";

import { revalidatePath } from "next/cache";

import { requireAuth } from "@/lib/auth";
import { createAutoPlan, createTemplatePlan } from "@/lib/plans";

export async function createPlanFromTemplate(formData: FormData) {
  const user = await requireAuth();
  const env = (formData.get("environment") === "GYM" ? "GYM" : "HOME") as
    | "HOME"
    | "GYM";

  await createTemplatePlan(user.id, env);
  revalidatePath("/dashboard");
}

export async function createAutoGeneratedPlan(formData: FormData) {
  const user = await requireAuth();

  const env = (formData.get("environment") === "GYM" ? "GYM" : "HOME") as
    | "HOME"
    | "GYM";
  const daysPerWeekRaw = Number(formData.get("daysPerWeek") ?? 3);
  const daysPerWeek = Math.min(4, Math.max(2, Number.isFinite(daysPerWeekRaw) ? daysPerWeekRaw : 3));

  await createAutoPlan(user.id, {
    environment: env,
    daysPerWeek,
  });

  revalidatePath("/dashboard");
}
